spring:
  application:
    name: DataWorkCloud

server:
  port: 20303
eureka:
  instance:
    hostname:
#    preferIpAddress: true
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://ip:port/eureka/
#  server:
#    enableSelfPreservation: false
  server:
    response-cache-update-interval-ms: 2000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000