server:
  port: 8294
spring:
  application:
    name: linkis-ps-metadatamanager-mysql

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.201:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml


