# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-config
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <!--
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License. See accompanying LICENSE file.
    -->

    <!-- Put site-specific property overrides in this file. -->

    <configuration>
       <property>
          <name>fs.default.name</name>
          <value>hdfs://localhost:9000</value> 
       </property>
    </configuration>
  hive-site.xml: "<?xml version=\"1.0\"?>\n<?xml-stylesheet type=\"text/xsl\" href=\"configuration.xsl\"?>\n<configuration>\n\t<property>\n\t  <name>javax.jdo.option.ConnectionURL</name>\n\t  <value>jdbc:mysql://127.0.0.1:3306/metastore?createDatabaseIfNotExist=true&amp;useSSL=false</value>\n\t  <description>JDBC connect string for a JDBC metastore</description>\n\t</property>\n\n\t<property>\n\t  <name>javax.jdo.option.ConnectionDriverName</name>\n\t  <value>com.mysql.jdbc.Driver</value>\n\t  <description>Driver class name for a JDBC metastore</description>\n\t</property>\n\n\t<property>\n\t  <name>javax.jdo.option.ConnectionUserName</name>\n\t  <value>root</value>\n\t  <description>username to use against metastore database</description>\n\t</property>\n\n\t<property>\n\t  <name>javax.jdo.option.ConnectionPassword</name>\n\t  <value>123456</value>\n\t  <description>password to use against metastore database</description>\n\t</property>\n\n<property>\n<name>hive.metastore.warehouse.dir</name>\n<value>/user/hive/warehouse</value>\n<description>location of default database for the warehouse</description>\n</property>\n\n<property>\n    <name>hive.metastore.schema.verification</name>\n    <value>false</value>\n</property>\n\n<property>\n\t<name>hive.cli.print.header</name>\n\t<value>true</value>\n</property>\n\n<property>\n\t<name>hive.cli.print.current.db</name>\n\t<value>true</value>\n</property>\n\n<property>\n<name>hive.metastore.uris</name>\n<value>thrift://127.0.0.1:9083</value>\n</property>\n\n</configuration>\n"
