apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-cg-entrance
  namespace: preprod
  labels:
    app: linkis-cg-entrance
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-cg-entrance
      version: v1
  template:
    metadata:
      labels:
        app: linkis-cg-entrance
        version: v1
    spec:
      volumes:
        - name: conf
          configMap: 
            name: linkis-config
        - name: hadoop-config
          configMap: 
            name: hadoop-config
        - name: hive-config
          configMap: 
            name: hive-config
        - name: spark-config
          configMap: 
            name: spark-config
      containers:
        - image: registry.mydomain.com/library/linkis-cg-entrance:1.2.0
          imagePullPolicy: Always
          name: linkis-cg-entrance
          ports:
            - containerPort: 9106
          env:
            - name: EUREKA_URL
              value: "http://linkis-mg-eureka:20303/eureka/"
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
          volumeMounts:
            - name: conf
              mountPath: /opt/linkis/linkis-cg-entrance/conf
            - name: hadoop-config
              mountPath: /usr/local/hadoop/etc/hadoop
            - name: hive-config
              mountPath: /usr/local/hive/conf
            - name: spark-config
              mountPath: /usr/local/spark/conf

