apiVersion: v1
kind: Service
metadata:
  name: linkis-mg-gateway
  namespace: preprod
  labels:
    app: linkis-mg-gateway
    service: linkis-mg-gateway
spec:
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      nodePort: 30358
  selector:
    app: linkis-mg-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkis-mg-gateway
  namespace: preprod
  labels:
    app: linkis-mg-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkis-mg-gateway
      version: v1
  template:
    metadata:
      labels:
        app: linkis-mg-gateway
        version: v1
    spec:
      volumes:
        - name: conf
          configMap: 
            name: linkis-config
      containers:
        - image: registry.mydomain.com/library/linkis-mg-gateway:1.2.0
          imagePullPolicy: Always
          name: linkis-mg-gateway
          ports:
            - containerPort: 9001
          env:
            - name: EUREKA_URL
              value: "http://linkis-mg-eureka:20303/eureka/"
            - name: START_PORT
              value: "9001"
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
          volumeMounts:
            - name: conf
              mountPath: /opt/linkis/linkis-mg-gateway/conf/

