#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build Backend

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        install: [ 'backend', 'spark' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 8
    - if: ${{ matrix.install == 'backend' }}
      name: Build backend by maven
      run:
        ./mvnw clean package
    - if: ${{ matrix.install == 'spark' }}
      name: install spark
      strategy:
        matrix:
          installSpark: [ 'init', '3.2','2.4' ]
      - if: ${{ matrix.installSpark == 'init' }}
        name: Build backend on ${{ matrix.installSpark }}
        run:
          ./mvnw -N install
      - if: ${{ matrix.installSpark == '3.2' }}
        name: Build backend on ${{ matrix.installSpark }}
        run:
          ./mvnw clean install -Pspark-3.2 -Phadoop-3.3 -Dmaven.test.skip=true
      - if: ${{ matrix.installSpark == '2.4' }}
        name: Build backend on ${{ matrix.installSpark }}
        run:
          ./mvnw clean install -Pspark-2.4-hadoop-3.3 -Phadoop-3.3 -Dmaven.test.skip=true

#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3.0.0
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
