# This is a basic workflow to help you get started with Actions

name: frontend
on:
  push:
  pull_request:
    branches:
      - master
      - branch-*
    types: [opened, synchronize]

jobs:
  run-e2e-tests-in-linkis-web:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/linkis/
          key: ${{ runner.os }}-linkis-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-linkis-
  
  run-tests-in-linkis-web-angular:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/linkis/
          key: ${{ runner.os }}-linkis-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-linkis-

  test-selenium-with-spark-module-for-spark-2-3:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/linkis/
          key: ${{ runner.os }}-linkis-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-linkis-
      - name: install environment
        run: |
          mvn install -pl linkis-public-enhancements -am
