name: frontend
on:
  push:
    paths:
      - '.github/workflows/ci_frontend.yml'
      - 'web/**'
  pull_request:
    paths:
      - '.github/workflows/ci_frontend.yml'
      - 'web/**'

jobs:
  run-tests-in-linkis-web:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/linkis/
          key: ${{ runner.os }}-linkis-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-linkis-
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          version: 8
      - name: Setup environment with python 3.7 and R
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python_3_with_R
          environment-file: testing/env_python_3_with_R.yml # 在 test 文化夹下加上 yml 文件，用于适配 python 版本
          python-version: 3.7
          auto-activate-base: false
