name: issue-robot

on:
  issues:
    types: [opened]

jobs:
  issueRobot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: "Translation into English in issue"
        uses: tomsun28/issues-translate-action@v2.5
        with:
          IS_MODIFY_TITLE: false
          # 非必须，决定是否需要修改issue标题内容   
          # 若是true，则机器人账户@Issues-translate-bot必须拥有修改此仓库issue权限。可以通过邀请@Issues-translate-bot加入仓库协作者实现。
          CUSTOM_BOT_NOTE: Bot detected the issue body's language is not English, translate it automatically.。

      - name: "Comment in issue"
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "Hi:\n* Thank you for your feedback, we have received your issue, Please wait patiently for a reply.\n*"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
