name: rat
on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*
    types: [opened, synchronize]

jobs:
  license-check:
    runs-on: ubuntu-20.04
    env:
      # Disable keepAlive and pool
      # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
      MAVEN_OPTS: >-
          -Xms1024M -Xmx2048M -XX:MaxMetaspaceSize=1024m -XX:-UseGCOverheadLimit -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dhttp.keepAlive=false
          -Dmaven.wagon.http.pool=false
          -Dmaven.wagon.http.retryHandler.count=3
    steps:
      - name: Check License Header # 检查许可证头
        uses: apache/skywalking-eyes@ec88b7d850018c8983f87729ea88549e100c5c82
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Check dependency license # 检查依赖许可证
        run: tools/dependencies/check-LICENSE.sh
      # - name: Check Rat
      #   run: mvn apache-rat:check -Prat -B
