name: rat
on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*
    types: [opened, synchronize]

jobs:
  license-check:
    runs-on: ubuntu-20.04
    env:
      # Disable keepAlive and pool
      # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
      MAVEN_OPTS: >-
          -Xms1024M -Xmx2048M -XX:MaxMetaspaceSize=1024m -XX:-UseGCOverheadLimit -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dhttp.keepAlive=false
          -Dmaven.wagon.http.pool=false
          -Dmaven.wagon.http.retryHandler.count=3
    steps:
      - name: Check License Header # 检查许可证头
        uses: apache/skywalking-eyes@main
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Compile # 编译检查
        run: |
          mvn -N install
          mvn clean install
      - name: Check dependency license # 检查依赖许可证
        run: |
         chmod 777 tools/dependencies/check-LICENSE.sh
         chmod 777 ./mvnw
         tools/dependencies/check-LICENSE.sh
      # - name: Check Rat 1
      #   run: mvn apache-rat:check -Prat -B
      # - name: Check Rat 1
      #   run: mvn apache-rat:check -Prat -B
